<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="CHIGOWDA-L480"><DocLocation><![CDATA[C:\Proj_Automation\Drivers\Driver1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Driver1]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Identity Cloud Service]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:52]]></Time>
<TimeTick>1630242952</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Identity Cloud Service]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:52]]></Time>
<TimeTick>1630242952</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[User name or email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["chiranth.gowda@mtn.com"]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:52]]></Time>
<TimeTick>1630242952</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[User name or email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["P@$$w0rdchi1@3"]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:52]]></Time>
<TimeTick>1630242952</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Sign In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:52]]></Time>
<TimeTick>1630242952</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[Sign In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" >
<Disp><![CDATA[Identity Cloud Service]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Welcome]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:57]]></Time>
<TimeTick>1630242957</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:45:57]]></Time>
<TimeTick>1630242957</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" >
<Disp><![CDATA[Welcome]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Oracle Applications]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:01]]></Time>
<TimeTick>1630242961</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[My Client Groups.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:01]]></Time>
<TimeTick>1630242961</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" >
<Disp><![CDATA[My Client Groups.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:04]]></Time>
<TimeTick>1630242964</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="38" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" >
<Disp><![CDATA[Oracle Applications]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Search Person - Person]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:09]]></Time>
<TimeTick>1630242969</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["188029"]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:09]]></Time>
<TimeTick>1630242969</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" >
<Disp><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:09]]></Time>
<TimeTick>1630242969</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Coleman, Prince Henry.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:10]]></Time>
<TimeTick>1630242970</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" >
<Disp><![CDATA[Coleman, Prince Henry.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Coleman, Prince Henry.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:10]]></Time>
<TimeTick>1630242970</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" >
<Disp><![CDATA[Coleman, Prince Henry.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:10]]></Time>
<TimeTick>1630242970</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" >
<Disp><![CDATA[Search Person - Person]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" >
<Disp><![CDATA[Identity Cloud Service]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Welcome]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:15]]></Time>
<TimeTick>1630242975</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Welcome]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:15]]></Time>
<TimeTick>1630242975</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:15]]></Time>
<TimeTick>1630242975</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="65" >
<Disp><![CDATA[Welcome]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Oracle Applications]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:15]]></Time>
<TimeTick>1630242975</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[My Client Groups.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:15]]></Time>
<TimeTick>1630242975</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" >
<Disp><![CDATA[My Client Groups.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:19]]></Time>
<TimeTick>1630242979</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" >
<Disp><![CDATA[Oracle Applications]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Search Person - Person]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:22]]></Time>
<TimeTick>1630242982</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["188029"]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:22]]></Time>
<TimeTick>1630242982</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="82" >
<Disp><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:22]]></Time>
<TimeTick>1630242982</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Coleman, Prince Henry.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:23]]></Time>
<TimeTick>1630242983</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="89" >
<Disp><![CDATA[Coleman, Prince Henry.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Tasks.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:33]]></Time>
<TimeTick>1630242993</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="107" >
<Disp><![CDATA[Tasks.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Absence Records.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:39]]></Time>
<TimeTick>1630242999</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="110" >
<Disp><![CDATA[Absence Records.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Absence Records.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:39]]></Time>
<TimeTick>1630242999</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="112" >
<Disp><![CDATA[Absence Records.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Close.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:39]]></Time>
<TimeTick>1630242999</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" >
<Disp><![CDATA[Close.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:39]]></Time>
<TimeTick>1630242999</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="118" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="81" >
<Disp><![CDATA[Search Person - Person]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="64" >
<Disp><![CDATA[Welcome]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Identity Cloud Service]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:46]]></Time>
<TimeTick>1630243006</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Welcome]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:46]]></Time>
<TimeTick>1630243006</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:46]]></Time>
<TimeTick>1630243006</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="123" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="122" >
<Disp><![CDATA[Welcome]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Oracle Applications]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:46]]></Time>
<TimeTick>1630243006</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[My Client Groups.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:46]]></Time>
<TimeTick>1630243006</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="127" >
<Disp><![CDATA[My Client Groups.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[WebElement_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:50]]></Time>
<TimeTick>1630243010</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="130" >
<Disp><![CDATA[WebElement_3.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="126" >
<Disp><![CDATA[Oracle Applications]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Search Person - Person]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:54]]></Time>
<TimeTick>1630243014</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["188164"]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:54]]></Time>
<TimeTick>1630243014</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="139" >
<Disp><![CDATA[_FOpt1:_FOr1:0:_FONSr2:0:MAt1:.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:54]]></Time>
<TimeTick>1630243014</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="142" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Dotcher, Felix.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:46:54]]></Time>
<TimeTick>1630243014</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="146" >
<Disp><![CDATA[Dotcher, Felix.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Tasks.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:47:00]]></Time>
<TimeTick>1630243020</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="156" >
<Disp><![CDATA[Tasks.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[View Compensation History.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:47:05]]></Time>
<TimeTick>1630243025</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="159" >
<Disp><![CDATA[View Compensation History.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[View Compensation History.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/29/2021 - 18:47:05]]></Time>
<TimeTick>1630243025</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="161" >
<Disp><![CDATA[View Compensation History.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/29/2021 - 18:47:11]]></Time>
<TimeTick>1630243031</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="164" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="138" >
<Disp><![CDATA[Search Person - Person]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="121" >
<Disp><![CDATA[Identity Cloud Service]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="8/29/2021 - 18:45:46" eTime="8/29/2021 - 18:47:11" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[Driver1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="8/29/2021 - 18:45:38" eTime="8/29/2021 - 18:47:11" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test Driver1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>